### ISSUE TITLE
zephir compile error

### ISSUE THREAD

**Issue by phpfeng** [dreamsxin/volt#1]
Copying new kernel files...
Preparing for PHP compilation...
Preparing configuration file...
Compiling...
In file included from ./php_volt.h:11,
                 from ./php_ext.h:4,
                 from kernel/memory.h:26:
./kernel/globals.h:48: error: expected specifier-qualifier-list before ‘zend_array’
kernel/main.h:285: error: expected declaration specifiers or ‘...’ before ‘zend_long’
kernel/string.h:26:28: error: zend_smart_str.h: No such file or directory
In file included from kernel/string.h:27:
./kernel/main.h:285: error: expected declaration specifiers or ‘...’ before ‘zend_long’
kernel/string.h:85: error: expected ‘)’ before ‘*’ token
In file included from ./php_volt.h:11,
                 from ./php_ext.h:4,
                 from kernel/fcall.h:24:
./kernel/globals.h:48: error: expected specifier-qualifier-list before ‘zend_array’
In file included from kernel/fcall.h:25:
./kernel/main.h:285: error: expected declaration specifiers or ‘...’ before ‘zend_long’
kernel/fcall.h: In function ‘zephir_return_call_function’:
kernel/fcall.h:342: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/php/include/php/Zend/zend_variables.h:51: note: expected ‘struct zval **’ but argument is of type ‘struct zval *’
kernel/fcall.h:357: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/php/include/php/Zend/zend_variables.h:51: note: expected ‘struct zval **’ but argument is of type ‘struct zval *’
kernel/fcall.h: In function ‘zephir_return_call_zval_function’:
kernel/fcall.h:370: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/php/include/php/Zend/zend_variables.h:51: note: expected ‘struct zval **’ but argument is of type ‘struct zval *’
kernel/fcall.h:385: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/php/include/php/Zend/zend_variables.h:51: note: expected ‘struct zval **’ but argument is of type ‘struct zval *’
kernel/fcall.h: In function ‘zephir_return_call_class_method’:
kernel/fcall.h:403: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/php/include/php/Zend/zend_variables.h:51: note: expected ‘struct zval **’ but argument is of type ‘struct zval *’
kernel/fcall.h:418: warning: passing argument 1 of ‘_zval_ptr_dtor’ from incompatible pointer type
/usr/local/php/include/php/Zend/zend_variables.h:51: note: expected ‘struct zval **’ but argument is of type ‘struct zval *’
kernel/fcall.h: In function ‘zephir_set_called_scope’:
kernel/fcall.h:474: error: ‘zend_execute_data’ has no member named ‘This’
kernel/fcall.h:475: error: ‘zend_execute_data’ has no member named ‘This’
kernel/fcall.h:477: error: ‘zend_execute_data’ has no member named ‘This’
kernel/fcall.h:478: error: ‘zend_execute_data’ has no member named ‘This’
kernel/fcall.h:480: error: ‘zend_execute_data’ has no member named ‘func’
kernel/fcall.h:481: error: ‘zend_execute_data’ has no member named ‘func’
kernel/fcall.h:481: error: ‘zend_execute_data’ has no member named ‘func’
In file included from kernel/array.h:27:
./kernel/globals.h:48: error: expected specifier-qualifier-list before ‘zend_array’
In file included from kernel/array.h:28:
./kernel/main.h:285: error: expected declaration specifiers or ‘...’ before ‘zend_long’
In file included from kernel/operators.h:26:
./kernel/main.h:285: error: expected declaration specifiers or ‘...’ before ‘zend_long’
In file included from kernel/concat.h:6:
./kernel/main.h:285: error: expected declaration specifiers or ‘...’ before ‘zend_long’
In file included from ./php_volt.h:11,
                 from ./php_ext.h:4,
                 from kernel/require.h:24:
./kernel/globals.h:48: error: expected specifier-qualifier-list before ‘zend_array’
In file included from kernel/exception.h:25:
./kernel/main.h:285: error: expected declaration specifiers or ‘...’ before ‘zend_long’
In file included from kernel/object.h:27:
./kernel/globals.h:48: error: expected specifier-qualifier-list before ‘zend_array’
In file included from kernel/object.h:28:
./kernel/main.h:285: error: expected declaration specifiers or ‘...’ before ‘zend_long’
kernel/globals.h:48: error: expected specifier-qualifier-list before ‘zend_array’

**Comment by dreamsxin** [comment]
你什么环境，PHP 是否存在多个版本？
要不你再更新下zephir，删除volt目录的ext/kernel目录，再编译下：
```shell
git clone https://github.com/dreamsxin/phalcon7-zephir.git
cd zephir/parser/parser
./build_linux.sh

cd zephir/parser
phpize && ./configure && make -j4 && sudo make install # 编译安装成功后，配置 extension=zephir_parser.so
```
